/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_donzbox_file_action_DiskSpace */

#ifndef _Included_com_donzbox_file_action_DiskSpace
#define _Included_com_donzbox_file_action_DiskSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_donzbox_file_action_DiskSpace
 * Method:    diskspace
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_donzbox_file_action_DiskSpace_diskspace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
